server:
  port: 9010

spring:
  application:
    name: INVENTORY-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27017/inventory_db

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
