server:
  port: 9006

spring:
  application:
    name: PAYMENT-SERVICE

  data:
    mongodb:
      uri: mongodb://localhost:27018/paymentdb

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true